import * as React from 'react';
import { View, Text, StyleSheet, ActivityIndicator } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { getSpeceficRepo } from '../network';
import { RepositoriesDtails } from '../customComponents';

class RepositoryView extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            issues:
            [
                {
                    "url": "https://api.github.com/repos/facebook/react/issues/21423",
                    "repository_url": "https://api.github.com/repos/facebook/react",
                    "labels_url": "https://api.github.com/repos/facebook/react/issues/21423/labels{/name}",
                    "comments_url": "https://api.github.com/repos/facebook/react/issues/21423/comments",
                    "events_url": "https://api.github.com/repos/facebook/react/issues/21423/events",
                    "html_url": "https://github.com/facebook/react/issues/21423",
                    "id": 875282284,
                    "node_id": "MDU6SXNzdWU4NzUyODIyODQ=",
                    "number": 21423,
                    "title": "Bug: Unable to \"force update\" children if not wrapped into a custom Component",
                    "user": {
                        "login": "ErnestBrandi",
                        "id": 9258131,
                        "node_id": "MDQ6VXNlcjkyNTgxMzE=",
                        "avatar_url": "https://avatars.githubusercontent.com/u/9258131?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/ErnestBrandi",
                        "html_url": "https://github.com/ErnestBrandi",
                        "followers_url": "https://api.github.com/users/ErnestBrandi/followers",
                        "following_url": "https://api.github.com/users/ErnestBrandi/following{/other_user}",
                        "gists_url": "https://api.github.com/users/ErnestBrandi/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/ErnestBrandi/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/ErnestBrandi/subscriptions",
                        "organizations_url": "https://api.github.com/users/ErnestBrandi/orgs",
                        "repos_url": "https://api.github.com/users/ErnestBrandi/repos",
                        "events_url": "https://api.github.com/users/ErnestBrandi/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/ErnestBrandi/received_events",
                        "type": "User",
                        "site_admin": false
                    },
                    "labels": [
                        {
                            "id": 155984160,
                            "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
                            "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
                            "name": "Status: Unconfirmed",
                            "color": "d4c5f9",
                            "default": false,
                            "description": "A potential issue that we haven't yet confirmed as a bug"
                        }
                    ],
                    "state": "open",
                    "locked": false,
                    "assignee": null,
                    "assignees": [],
                    "milestone": null,
                    "comments": 1,
                    "created_at": "2021-05-04T09:33:47Z",
                    "updated_at": "2021-05-04T11:32:55Z",
                    "closed_at": null,
                    "author_association": "NONE",
                    "active_lock_reason": null,
                    "body": "React version: 17.0.2\r\n\r\n## The current behavior\r\n\r\nI am working on a component that would wrap a React Element in order to be able to update it at will.\r\n```\r\n<Wrapper>\r\n   {/* JSX */}\r\n</Wrapper>\r\n\r\nconst Wrapper = ({ children }) => {\r\n  // force update by changing state or so\r\n  return React.cloneElement(children);\r\n};\r\n```\r\nWhat I have noticed is : \r\n\r\n- if the \"children\", passed down as a props to the wrapper, is a custom component it behaves the way I expect to\r\n```\r\nfunction Child() {\r\n  return <div>{new Date().toString()}</div>;\r\n}\r\n\r\n<Wrapper>\r\n  <Child />\r\n</Wrapper>\r\n```\r\n- if instead it is a simple \"html style\" element it doesn't get updated\r\n```\r\n<Wrapper>\r\n  <div>{new Date().toString()}</div>\r\n</Wrapper>\r\n```\r\nI've played around with this quite a bit, for example using `React.createElement` on the children and switching between two different types (`div` and `span` for instance), as it says in the [documentation](https://reactjs.org/docs/reconciliation.html#elements-of-different-types) that\r\n\r\n> Any components below the root will also get unmounted and have their state destroyed.\r\n\r\nbut it did not help.\r\n## The expected behavior\r\nI would expect the two options to behave the same way.\r\n## Example\r\n[![Edit react-update-element](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-update-element-l6qz4?fontsize=14&hidenavigation=1&theme=dark)\r\n\r\n",
                    "performed_via_github_app": null
                },
                {
                    "url": "https://api.github.com/repos/facebook/react/issues/21422",
                    "repository_url": "https://api.github.com/repos/facebook/react",
                    "labels_url": "https://api.github.com/repos/facebook/react/issues/21422/labels{/name}",
                    "comments_url": "https://api.github.com/repos/facebook/react/issues/21422/comments",
                    "events_url": "https://api.github.com/repos/facebook/react/issues/21422/events",
                    "html_url": "https://github.com/facebook/react/issues/21422",
                    "id": 875246465,
                    "node_id": "MDU6SXNzdWU4NzUyNDY0NjU=",
                    "number": 21422,
                    "title": "Bug(?): ESLint react-hooks/rules-of-hooks not working in arrow functions with styled components",
                    "user": {
                        "login": "vinassefranche",
                        "id": 15926755,
                        "node_id": "MDQ6VXNlcjE1OTI2NzU1",
                        "avatar_url": "https://avatars.githubusercontent.com/u/15926755?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/vinassefranche",
                        "html_url": "https://github.com/vinassefranche",
                        "followers_url": "https://api.github.com/users/vinassefranche/followers",
                        "following_url": "https://api.github.com/users/vinassefranche/following{/other_user}",
                        "gists_url": "https://api.github.com/users/vinassefranche/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/vinassefranche/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/vinassefranche/subscriptions",
                        "organizations_url": "https://api.github.com/users/vinassefranche/orgs",
                        "repos_url": "https://api.github.com/users/vinassefranche/repos",
                        "events_url": "https://api.github.com/users/vinassefranche/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/vinassefranche/received_events",
                        "type": "User",
                        "site_admin": false
                    },
                    "labels": [
                        {
                            "id": 155984160,
                            "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
                            "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
                            "name": "Status: Unconfirmed",
                            "color": "d4c5f9",
                            "default": false,
                            "description": "A potential issue that we haven't yet confirmed as a bug"
                        }
                    ],
                    "state": "open",
                    "locked": false,
                    "assignee": null,
                    "assignees": [],
                    "milestone": null,
                    "comments": 0,
                    "created_at": "2021-05-04T08:48:38Z",
                    "updated_at": "2021-05-04T08:48:38Z",
                    "closed_at": null,
                    "author_association": "NONE",
                    "active_lock_reason": null,
                    "body": "Full description is [here](https://github.com/styled-components/styled-components/issues/3478) I don't know if it's an issue on styled-components or on react side so I'm just letting you know.\r\n\r\nThanks in advance for any anwser!",
                    "performed_via_github_app": null
                }
            ],
            contributors: 
            [
                {
                    "login": "zpao",
                    "id": 8445,
                    "node_id": "MDQ6VXNlcjg0NDU=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/8445?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/zpao",
                    "html_url": "https://github.com/zpao",
                    "followers_url": "https://api.github.com/users/zpao/followers",
                    "following_url": "https://api.github.com/users/zpao/following{/other_user}",
                    "gists_url": "https://api.github.com/users/zpao/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/zpao/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/zpao/subscriptions",
                    "organizations_url": "https://api.github.com/users/zpao/orgs",
                    "repos_url": "https://api.github.com/users/zpao/repos",
                    "events_url": "https://api.github.com/users/zpao/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/zpao/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 1778
                },
                {
                    "login": "gaearon",
                    "id": 810438,
                    "node_id": "MDQ6VXNlcjgxMDQzOA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/810438?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/gaearon",
                    "html_url": "https://github.com/gaearon",
                    "followers_url": "https://api.github.com/users/gaearon/followers",
                    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
                    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
                    "organizations_url": "https://api.github.com/users/gaearon/orgs",
                    "repos_url": "https://api.github.com/users/gaearon/repos",
                    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/gaearon/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 1597
                },
                {
                    "login": "bvaughn",
                    "id": 29597,
                    "node_id": "MDQ6VXNlcjI5NTk3",
                    "avatar_url": "https://avatars.githubusercontent.com/u/29597?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/bvaughn",
                    "html_url": "https://github.com/bvaughn",
                    "followers_url": "https://api.github.com/users/bvaughn/followers",
                    "following_url": "https://api.github.com/users/bvaughn/following{/other_user}",
                    "gists_url": "https://api.github.com/users/bvaughn/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/bvaughn/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/bvaughn/subscriptions",
                    "organizations_url": "https://api.github.com/users/bvaughn/orgs",
                    "repos_url": "https://api.github.com/users/bvaughn/repos",
                    "events_url": "https://api.github.com/users/bvaughn/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/bvaughn/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 1530
                },
                {
                    "login": "sophiebits",
                    "id": 6820,
                    "node_id": "MDQ6VXNlcjY4MjA=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/6820?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/sophiebits",
                    "html_url": "https://github.com/sophiebits",
                    "followers_url": "https://api.github.com/users/sophiebits/followers",
                    "following_url": "https://api.github.com/users/sophiebits/following{/other_user}",
                    "gists_url": "https://api.github.com/users/sophiebits/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/sophiebits/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/sophiebits/subscriptions",
                    "organizations_url": "https://api.github.com/users/sophiebits/orgs",
                    "repos_url": "https://api.github.com/users/sophiebits/repos",
                    "events_url": "https://api.github.com/users/sophiebits/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/sophiebits/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 1268
                },
                {
                    "login": "acdlite",
                    "id": 3624098,
                    "node_id": "MDQ6VXNlcjM2MjQwOTg=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/3624098?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/acdlite",
                    "html_url": "https://github.com/acdlite",
                    "followers_url": "https://api.github.com/users/acdlite/followers",
                    "following_url": "https://api.github.com/users/acdlite/following{/other_user}",
                    "gists_url": "https://api.github.com/users/acdlite/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/acdlite/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/acdlite/subscriptions",
                    "organizations_url": "https://api.github.com/users/acdlite/orgs",
                    "repos_url": "https://api.github.com/users/acdlite/repos",
                    "events_url": "https://api.github.com/users/acdlite/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/acdlite/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 943
                },
                {
                    "login": "sebmarkbage",
                    "id": 63648,
                    "node_id": "MDQ6VXNlcjYzNjQ4",
                    "avatar_url": "https://avatars.githubusercontent.com/u/63648?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/sebmarkbage",
                    "html_url": "https://github.com/sebmarkbage",
                    "followers_url": "https://api.github.com/users/sebmarkbage/followers",
                    "following_url": "https://api.github.com/users/sebmarkbage/following{/other_user}",
                    "gists_url": "https://api.github.com/users/sebmarkbage/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/sebmarkbage/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/sebmarkbage/subscriptions",
                    "organizations_url": "https://api.github.com/users/sebmarkbage/orgs",
                    "repos_url": "https://api.github.com/users/sebmarkbage/repos",
                    "events_url": "https://api.github.com/users/sebmarkbage/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/sebmarkbage/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 937
                },
                {
                    "login": "jimfb",
                    "id": 9595985,
                    "node_id": "MDQ6VXNlcjk1OTU5ODU=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/9595985?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/jimfb",
                    "html_url": "https://github.com/jimfb",
                    "followers_url": "https://api.github.com/users/jimfb/followers",
                    "following_url": "https://api.github.com/users/jimfb/following{/other_user}",
                    "gists_url": "https://api.github.com/users/jimfb/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/jimfb/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/jimfb/subscriptions",
                    "organizations_url": "https://api.github.com/users/jimfb/orgs",
                    "repos_url": "https://api.github.com/users/jimfb/repos",
                    "events_url": "https://api.github.com/users/jimfb/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/jimfb/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 456
                },
                {
                    "login": "trueadm",
                    "id": 1519870,
                    "node_id": "MDQ6VXNlcjE1MTk4NzA=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1519870?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/trueadm",
                    "html_url": "https://github.com/trueadm",
                    "followers_url": "https://api.github.com/users/trueadm/followers",
                    "following_url": "https://api.github.com/users/trueadm/following{/other_user}",
                    "gists_url": "https://api.github.com/users/trueadm/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/trueadm/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/trueadm/subscriptions",
                    "organizations_url": "https://api.github.com/users/trueadm/orgs",
                    "repos_url": "https://api.github.com/users/trueadm/repos",
                    "events_url": "https://api.github.com/users/trueadm/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/trueadm/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 436
                },
                {
                    "login": "petehunt",
                    "id": 239742,
                    "node_id": "MDQ6VXNlcjIzOTc0Mg==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/239742?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/petehunt",
                    "html_url": "https://github.com/petehunt",
                    "followers_url": "https://api.github.com/users/petehunt/followers",
                    "following_url": "https://api.github.com/users/petehunt/following{/other_user}",
                    "gists_url": "https://api.github.com/users/petehunt/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/petehunt/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/petehunt/subscriptions",
                    "organizations_url": "https://api.github.com/users/petehunt/orgs",
                    "repos_url": "https://api.github.com/users/petehunt/repos",
                    "events_url": "https://api.github.com/users/petehunt/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/petehunt/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 332
                },
                {
                    "login": "chenglou",
                    "id": 1909539,
                    "node_id": "MDQ6VXNlcjE5MDk1Mzk=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/1909539?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/chenglou",
                    "html_url": "https://github.com/chenglou",
                    "followers_url": "https://api.github.com/users/chenglou/followers",
                    "following_url": "https://api.github.com/users/chenglou/following{/other_user}",
                    "gists_url": "https://api.github.com/users/chenglou/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/chenglou/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/chenglou/subscriptions",
                    "organizations_url": "https://api.github.com/users/chenglou/orgs",
                    "repos_url": "https://api.github.com/users/chenglou/repos",
                    "events_url": "https://api.github.com/users/chenglou/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/chenglou/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 222
                },
                {
                    "login": "vjeux",
                    "id": 197597,
                    "node_id": "MDQ6VXNlcjE5NzU5Nw==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/197597?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/vjeux",
                    "html_url": "https://github.com/vjeux",
                    "followers_url": "https://api.github.com/users/vjeux/followers",
                    "following_url": "https://api.github.com/users/vjeux/following{/other_user}",
                    "gists_url": "https://api.github.com/users/vjeux/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/vjeux/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/vjeux/subscriptions",
                    "organizations_url": "https://api.github.com/users/vjeux/orgs",
                    "repos_url": "https://api.github.com/users/vjeux/repos",
                    "events_url": "https://api.github.com/users/vjeux/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/vjeux/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 207
                },
                {
                    "login": "benjamn",
                    "id": 5750,
                    "node_id": "MDQ6VXNlcjU3NTA=",
                    "avatar_url": "https://avatars.githubusercontent.com/u/5750?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/benjamn",
                    "html_url": "https://github.com/benjamn",
                    "followers_url": "https://api.github.com/users/benjamn/followers",
                    "following_url": "https://api.github.com/users/benjamn/following{/other_user}",
                    "gists_url": "https://api.github.com/users/benjamn/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/benjamn/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/benjamn/subscriptions",
                    "organizations_url": "https://api.github.com/users/benjamn/orgs",
                    "repos_url": "https://api.github.com/users/benjamn/repos",
                    "events_url": "https://api.github.com/users/benjamn/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/benjamn/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 140
                },
                {
                    "login": "yungsters",
                    "id": 55161,
                    "node_id": "MDQ6VXNlcjU1MTYx",
                    "avatar_url": "https://avatars.githubusercontent.com/u/55161?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/yungsters",
                    "html_url": "https://github.com/yungsters",
                    "followers_url": "https://api.github.com/users/yungsters/followers",
                    "following_url": "https://api.github.com/users/yungsters/following{/other_user}",
                    "gists_url": "https://api.github.com/users/yungsters/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/yungsters/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/yungsters/subscriptions",
                    "organizations_url": "https://api.github.com/users/yungsters/orgs",
                    "repos_url": "https://api.github.com/users/yungsters/repos",
                    "events_url": "https://api.github.com/users/yungsters/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/yungsters/received_events",
                    "type": "User",
                    "site_admin": false,
                    "contributions": 122
                }
            ],
            repo: {
                    "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
                    "archived": false,
                    "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
                    "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
                    "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
                    "clone_url": "https://github.com/facebook/react.git",
                    "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
                    "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
                    "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
                    "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
                    "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
                    "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
                    "created_at": "2013-05-24T16:15:54Z",
                    "default_branch": "master",
                    "deployments_url": "https://api.github.com/repos/facebook/react/deployments",
                    "description": "A declarative, efficient, and flexible JavaScript library for building user interfaces.",
                    "disabled": false,
                    "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
                    "events_url": "https://api.github.com/repos/facebook/react/events",
                    "fork": false,
                    "forks": 33776,
                    "forks_count": 33776,
                    "forks_url": "https://api.github.com/repos/facebook/react/forks",
                    "full_name": "facebook/react",
                    "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
                    "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
                    "git_url": "git://github.com/facebook/react.git",
                    "has_downloads": true,
                    "has_issues": true,
                    "has_pages": true,
                    "has_projects": true,
                    "has_wiki": true,
                    "homepage": "https://reactjs.org",
                    "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
                    "html_url": "https://github.com/facebook/react",
                    "id": 10270250,
                    "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
                    "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
                    "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
                    "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
                    "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
                    "language": "JavaScript",
                    "languages_url": "https://api.github.com/repos/facebook/react/languages",
                    "license": {
                      "key": "mit",
                      "name": "MIT License",
                      "node_id": "MDc6TGljZW5zZTEz",
                      "spdx_id": "MIT",
                      "url": "https://api.github.com/licenses/mit"
                    },
                    "merges_url": "https://api.github.com/repos/facebook/react/merges",
                    "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
                    "mirror_url": null,
                    "name": "react",
                    "network_count": 33776,
                    "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
                    "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
                    "open_issues": 709,
                    "open_issues_count": 709,
                    "organization": {
                      "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                      "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                      "followers_url": "https://api.github.com/users/facebook/followers",
                      "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                      "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                      "gravatar_id": "",
                      "html_url": "https://github.com/facebook",
                      "id": 69631,
                      "login": "facebook",
                      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                      "organizations_url": "https://api.github.com/users/facebook/orgs",
                      "received_events_url": "https://api.github.com/users/facebook/received_events",
                      "repos_url": "https://api.github.com/users/facebook/repos",
                      "site_admin": false,
                      "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                      "type": "Organization",
                      "url": "https://api.github.com/users/facebook"
                    },
                    "owner": {
                      "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
                      "events_url": "https://api.github.com/users/facebook/events{/privacy}",
                      "followers_url": "https://api.github.com/users/facebook/followers",
                      "following_url": "https://api.github.com/users/facebook/following{/other_user}",
                      "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
                      "gravatar_id": "",
                      "html_url": "https://github.com/facebook",
                      "id": 69631,
                      "login": "facebook",
                      "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
                      "organizations_url": "https://api.github.com/users/facebook/orgs",
                      "received_events_url": "https://api.github.com/users/facebook/received_events",
                      "repos_url": "https://api.github.com/users/facebook/repos",
                      "site_admin": false,
                      "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
                      "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
                      "type": "Organization",
                      "url": "https://api.github.com/users/facebook"
                    },
                    "private": false,
                    "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
                    "pushed_at": "2021-05-04T15:40:16Z",
                    "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
                    "size": 165120,
                    "ssh_url": "git@github.com:facebook/react.git",
                    "stargazers_count": 167853,
                    "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
                    "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
                    "subscribers_count": 6722,
                    "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
                    "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
                    "svn_url": "https://github.com/facebook/react",
                    "tags_url": "https://api.github.com/repos/facebook/react/tags",
                    "teams_url": "https://api.github.com/repos/facebook/react/teams",
                    "temp_clone_token": null,
                    "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
                    "updated_at": "2021-05-04T15:40:32Z",
                    "url": "https://api.github.com/repos/facebook/react",
                    "watchers": 167853,
                    "watchers_count": 167853
            }
        }
    }

    componentDidMount = async () => {
        /*const response = await getSpeceficRepo(this.props.route.params.owner, this.props.route.params.repos)
        this.setState({repo: response});*/
    }

    render() {
        const { colors } = this.props.theme;

        return (
            <View style={styles.container}>
                {this.state.repo.owner === undefined ? 
                    <ActivityIndicator size="large" color="#EE6C4D" />
                :
                    <RepositoriesDtails repo={this.state.repo} contributors={this.state.contributors} issues={this.state.issues} />
                }
            </View>
        )

    }

}

export default function(props) {
    const theme = useTheme();
  
    return <RepositoryView {...props} theme={theme} />;
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center'
    }
})